import { Agent, Agency, Lead, Property, SubscriptionPlan, MessageTemplate } from '../types';

// Mock Agents
export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao.silva@example.com',
    phone: '11999887766',
    role: 'agent',
    photoUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
    createdAt: new Date('2023-01-15'),
    leadsCount: 12,
    conversionRate: 0.25,
  },
  {
    id: '2',
    name: 'Maria Oliveira',
    email: 'maria.oliveira@example.com',
    phone: '11988776655',
    role: 'agent',
    photoUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
    createdAt: new Date('2023-02-20'),
    leadsCount: 18,
    conversionRate: 0.33,
    agencyId: '1',
  },
  {
    id: '3',
    name: 'Carlos Pereira',
    email: 'carlos.pereira@example.com',
    phone: '11977665544',
    role: 'agent',
    photoUrl: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
    createdAt: new Date('2023-03-10'),
    leadsCount: 8,
    conversionRate: 0.38,
    agencyId: '1',
  },
  {
    id: '4',
    name: 'Ana Costa',
    email: 'ana.costa@example.com',
    phone: '11966554433',
    role: 'agent',
    photoUrl: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg',
    createdAt: new Date('2023-04-05'),
    leadsCount: 15,
    conversionRate: 0.27,
  },
];

// Mock Agencies
export const mockAgencies: Agency[] = [
  {
    id: '1',
    name: 'Imobiliária Excelência',
    email: 'contato@excelencia.com.br',
    phone: '1133445566',
    role: 'agency',
    photoUrl: 'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg',
    createdAt: new Date('2022-11-05'),
    agents: ['2', '3'],
  },
];

// Mock Leads - Expandido com os exemplos solicitados
export const mockLeads: Lead[] = [
  // Leads solicitados
  {
    id: '1',
    name: 'João da Silva',
    email: 'joao.silva.lead@example.com',
    phone: '11912345678',
    source: 'whatsapp',
    status: 'hot',
    agentId: '1',
    notes: 'Lead muito interessado, entrou em contato via WhatsApp perguntando sobre apartamentos na zona sul.',
    createdAt: new Date('2023-06-25'),
    updatedAt: new Date('2023-06-25'),
  },
  {
    id: '2',
    name: 'Maria Oliveira',
    email: 'maria.oliveira.lead@example.com',
    phone: '11987654321',
    source: 'referral',
    status: 'warm',
    agentId: '1',
    notes: 'Indicada por cliente anterior. Procura casa com quintal para os filhos.',
    createdAt: new Date('2023-06-24'),
    updatedAt: new Date('2023-06-24'),
  },
  {
    id: '3',
    name: 'José Pedro',
    email: 'jose.pedro@example.com',
    phone: '11976543210',
    source: 'manual',
    status: 'cold',
    agentId: '2',
    notes: 'Cadastrado manualmente após contato telefônico. Ainda está pesquisando.',
    createdAt: new Date('2023-06-23'),
    updatedAt: new Date('2023-06-23'),
  },
  {
    id: '4',
    name: 'Carla Menezes',
    email: 'carla.menezes@example.com',
    phone: '11965432109',
    source: 'website',
    status: 'hot',
    agentId: '2',
    notes: 'Preencheu formulário no site demonstrando muito interesse. Quer agendar visita urgente.',
    createdAt: new Date('2023-06-22'),
    updatedAt: new Date('2023-06-22'),
  },
  // Leads adicionais para completar o conjunto
  {
    id: '5',
    name: 'Ana Beatriz Santos',
    email: 'ana.beatriz@example.com',
    phone: '11954321098',
    source: 'website',
    status: 'warm',
    agentId: '1',
    notes: 'Interessada em apartamentos de 2 quartos na zona sul. Orçamento até R$ 800 mil.',
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2023-06-15'),
  },
  {
    id: '6',
    name: 'Roberto Almeida',
    email: 'roberto.almeida@example.com',
    phone: '11943210987',
    source: 'referral',
    status: 'hot',
    agentId: '3',
    notes: 'Investidor experiente buscando imóveis comerciais para renda. Tem capital disponível.',
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2023-06-16'),
  },
  {
    id: '7',
    name: 'Camila Santos',
    email: 'camila.santos@example.com',
    phone: '11932109876',
    source: 'whatsapp',
    status: 'warm',
    agentId: '3',
    notes: 'Primeira compra. Ainda está pesquisando e conhecendo o mercado.',
    createdAt: new Date('2023-06-14'),
    updatedAt: new Date('2023-06-14'),
  },
  {
    id: '8',
    name: 'Fernando Costa',
    email: 'fernando.costa@example.com',
    phone: '11921098765',
    source: 'manual',
    status: 'cold',
    agentId: '2',
    notes: 'Interessado em imóveis na praia para temporada. Ainda avaliando opções.',
    createdAt: new Date('2023-06-22'),
    updatedAt: new Date('2023-06-22'),
  },
  {
    id: '9',
    name: 'Gabriela Lima',
    email: 'gabriela.lima@example.com',
    phone: '11910987654',
    source: 'website',
    status: 'hot',
    agentId: '4',
    notes: 'Procura apartamento próximo ao trabalho na Faria Lima. Orçamento até R$ 1.2 milhão.',
    createdAt: new Date('2023-06-16'),
    updatedAt: new Date('2023-06-17'),
  },
  {
    id: '10',
    name: 'Ricardo Mendes',
    email: 'ricardo.mendes@example.com',
    phone: '11909876543',
    source: 'referral',
    status: 'warm',
    agentId: '1',
    notes: 'Quer trocar apartamento atual por casa. Já tem imóvel para dar de entrada.',
    createdAt: new Date('2023-06-18'),
    updatedAt: new Date('2023-06-19'),
  },
];

// Mock Properties - Expandido com os exemplos solicitados
export const mockProperties: Property[] = [
  // Imóveis solicitados
  {
    id: '1',
    title: 'Apartamento Vista Mar',
    description: 'Lindo apartamento com vista para o mar, acabamento de primeira qualidade e localização privilegiada.',
    salePrice: 450000,
    location: {
      neighborhood: 'Praia Grande',
      city: 'Santos',
      state: 'SP',
    },
    features: {
      bedrooms: 3,
      bathrooms: 2,
      parkingSpaces: 1,
      builtArea: 85,
      totalArea: 85,
    },
    benefits: [
      'Vista para o mar',
      'Próximo à praia',
      'Comércio local',
      'Transporte público',
      'Área de lazer',
      'Segurança 24h',
    ],
    photos: [
      'https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg',
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg',
    ],
    status: 'available',
    ownerId: '1',
    createdAt: new Date('2023-06-20'),
    updatedAt: new Date('2023-06-20'),
  },
  {
    id: '2',
    title: 'Casa no Condomínio Solar',
    description: 'Excelente casa em condomínio fechado com área de lazer completa, segurança 24h e muito verde.',
    salePrice: 690000,
    location: {
      neighborhood: 'Condomínio Solar',
      city: 'Cotia',
      state: 'SP',
    },
    features: {
      bedrooms: 4,
      bathrooms: 3,
      parkingSpaces: 2,
      builtArea: 150,
      totalArea: 300,
    },
    benefits: [
      'Condomínio fechado',
      'Segurança 24h',
      'Área de lazer completa',
      'Piscina',
      'Quadra esportiva',
      'Próximo a escolas',
    ],
    photos: [
      'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg',
      'https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg',
    ],
    status: 'available',
    ownerId: '2',
    createdAt: new Date('2023-06-19'),
    updatedAt: new Date('2023-06-19'),
  },
  {
    id: '3',
    title: 'Kitnet no Centro',
    description: 'Kitnet funcional e bem localizada no centro da cidade, ideal para estudantes ou profissionais.',
    salePrice: 190000,
    location: {
      neighborhood: 'Centro',
      city: 'São Paulo',
      state: 'SP',
    },
    features: {
      bedrooms: 1,
      bathrooms: 1,
      parkingSpaces: 0,
      builtArea: 35,
      totalArea: 35,
    },
    benefits: [
      'Centro da cidade',
      'Próximo ao metrô',
      'Comércio local',
      'Transporte público',
      'Universidades próximas',
      'Vida noturna',
    ],
    photos: [
      'https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg',
      'https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg',
    ],
    status: 'reserved',
    ownerId: '3',
    createdAt: new Date('2023-06-18'),
    updatedAt: new Date('2023-06-21'),
  },
  {
    id: '4',
    title: 'Cobertura Luxo',
    description: 'Cobertura de alto padrão com acabamento luxuoso, piscina privativa e vista panorâmica da cidade.',
    salePrice: 1200000,
    location: {
      neighborhood: 'Jardins',
      city: 'São Paulo',
      state: 'SP',
    },
    features: {
      bedrooms: 4,
      bathrooms: 4,
      parkingSpaces: 3,
      builtArea: 220,
      totalArea: 300,
    },
    benefits: [
      'Piscina privativa',
      'Vista panorâmica',
      'Acabamento de luxo',
      'Localização nobre',
      'Área gourmet',
      'Elevador privativo',
    ],
    photos: [
      'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg',
      'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg',
    ],
    status: 'sold',
    ownerId: '4',
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2023-06-20'),
  },
  // Imóveis adicionais para completar o portfólio
  {
    id: '5',
    title: 'Apartamento Luxuoso em Moema',
    description: 'Lindo apartamento com acabamento de alto padrão, próximo ao parque Ibirapuera.',
    salePrice: 1200000,
    appraisalValue: 1250000,
    location: {
      address: 'Alameda dos Nhambiquaras, 500',
      neighborhood: 'Moema',
      city: 'São Paulo',
      state: 'SP',
    },
    features: {
      bedrooms: 3,
      bathrooms: 2,
      parkingSpaces: 2,
      builtArea: 120,
      totalArea: 150,
    },
    benefits: [
      'Próximo ao metrô',
      'Academia no condomínio',
      'Piscina',
      'Segurança 24h',
      'Próximo ao Parque Ibirapuera',
      'Área gourmet',
    ],
    photos: [
      'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg',
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg',
    ],
    status: 'available',
    ownerId: '1',
    createdAt: new Date('2023-05-10'),
    updatedAt: new Date('2023-05-15'),
  },
  {
    id: '6',
    title: 'Casa em Condomínio Fechado - Granja Viana',
    description: 'Excelente casa em condomínio seguro, com ampla área de lazer.',
    salePrice: 900000,
    location: {
      neighborhood: 'Granja Viana',
      city: 'Cotia',
      state: 'SP',
    },
    features: {
      bedrooms: 4,
      bathrooms: 3,
      parkingSpaces: 3,
      builtArea: 200,
      totalArea: 350,
    },
    benefits: [
      'Condomínio com segurança 24h',
      'Área de lazer completa',
      'Jardim amplo',
      'Próximo a escolas',
      'Clube com piscina',
      'Quadra de tênis',
    ],
    photos: [
      'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg',
      'https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg',
    ],
    status: 'available',
    ownerId: '2',
    createdAt: new Date('2023-05-12'),
    updatedAt: new Date('2023-05-16'),
  },
  {
    id: '7',
    title: 'Sala Comercial Centro Empresarial',
    description: 'Sala comercial em prédio novo com excelente localização no centro financeiro.',
    salePrice: 550000,
    location: {
      neighborhood: 'Centro',
      city: 'São Paulo',
      state: 'SP',
    },
    features: {
      bedrooms: 0,
      bathrooms: 1,
      parkingSpaces: 1,
      builtArea: 50,
      totalArea: 50,
    },
    benefits: [
      'Prédio com segurança',
      'Próximo ao metrô',
      'Ar condicionado instalado',
      'Piso elevado',
      'Recepção 24h',
      'Elevadores modernos',
    ],
    photos: [
      'https://images.pexels.com/photos/260931/pexels-photo-260931.jpeg',
      'https://images.pexels.com/photos/1444416/pexels-photo-1444416.jpeg',
    ],
    status: 'available',
    ownerId: '3',
    createdAt: new Date('2023-04-20'),
    updatedAt: new Date('2023-05-10'),
  },
];

// Mock Message Templates
export const mockMessageTemplates: MessageTemplate[] = [
  {
    id: '1',
    title: 'Saudação Inicial',
    content: 'Olá {nome}, tudo bem? Aqui é {corretor} da {imobiliária}. Vi que você tem interesse em imóveis na nossa região. Como posso ajudar?',
    userId: '1',
    type: 'greeting',
  },
  {
    id: '2',
    title: 'Documentação Necessária',
    content: 'Olá {nome}, para darmos andamento no processo, precisamos dos seguintes documentos:\n- RG e CPF\n- Comprovante de residência\n- Comprovante de renda\nPoderia nos enviar?',
    userId: '1',
    type: 'documents',
  },
  {
    id: '3',
    title: 'Agendamento de Visita',
    content: 'Olá {nome}, gostaria de agendar uma visita ao imóvel {título_imóvel}? Temos disponibilidade nos seguintes horários:\n- Segunda-feira, 14h\n- Terça-feira, 10h\n- Quarta-feira, 16h\nQual seria melhor para você?',
    userId: '2',
    type: 'visit',
  },
];

// Get subscription limits
export const getSubscriptionLimits = (plan: SubscriptionPlan) => {
  switch (plan) {
    case 'free':
      return {
        maxLeads: 20,
        maxProperties: 5,
        canAddAgents: false,
        maxAgents: 0,
        unlimited: false,
      };
    case 'agent-premium':
      return {
        maxLeads: Infinity,
        maxProperties: Infinity,
        canAddAgents: false,
        maxAgents: 0,
        unlimited: true,
      };
    case 'agency-premium':
      return {
        maxLeads: Infinity,
        maxProperties: Infinity,
        canAddAgents: true,
        maxAgents: Infinity,
        unlimited: true,
      };
    default:
      return {
        maxLeads: 20,
        maxProperties: 5,
        canAddAgents: false,
        maxAgents: 0,
        unlimited: false,
      };
  }
};